### ISSUE TITLE
Uncaught Error: Call to undefined function edd_get_option()

### ISSUE THREAD

**Issue by bobbingwide** [bobbingwide/oik-sc-help#8]
I found several Fatal errors in the debug.log for `s.b/oikcom`
```
[11-Aug-2023 13:30:18 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function edd_get_option() in C:\apache\htdocs\wordpress\wp-content\plugins\oik-sc-help\shortcodes\easy-digital-downloads.php:329
Stack trace:
#0 C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\oik-sc-help.php(170): purchase_link__syntax('purchase_link')
#1 C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\oik-sc-help.php(186): _bw_lazy_sc_syntax('purchase_link')
#2 C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\bobbfunc.php(909): bw_lazy_sc_syntax('purchase_link', NULL)
#3 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(310): bw_sc_syntax('purchase_link')
#4 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#5 C:\apache\htdocs\oikcom\wp-includes\plugin.php(517): WP_Hook->do_action(Array)
#6 C:\apache\htdocs\wordpress\wp-content\plugins\oik\shortcodes\oik-codes.php(298): do_action('bw_sc_syntax', 'purchase_link')
#7 C:\apache\htdocs\wordpress\wp-content\plugins\oik\libs\oik-shortcodes.php(229): bw_code(Array, '', 'bw_code')
#8 C:\apache\htdocs\oikcom\wp-includes\shortcodes.php(395): bw_shortcode_event(Array, '', 'bw_code')
#9 C:\apache\htdocs\wordpress\wp-content\plugins\oik-css\includes\shortcodes-earlier.php(118): do_shortcode_tag(Array)
#10 [internal function]: do_shortcode_tag_earlier(Array)
#11 C:\apache\htdocs\wordpress\wp-content\plugins\oik-css\includes\shortcodes-earlier.php(95): preg_replace_callback('/\\[(\\[?)(bw_cod...', 'do_shortcode_ta...', 'text parameter ...')
#12 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(310): do_shortcode_earlier('text parameter ...')
#13 C:\apache\htdocs\oikcom\wp-includes\plugin.php(205): WP_Hook->apply_filters('text parameter ...', Array)
#14 C:\apache\htdocs\wordpress\wp-content\plugins\wordpress-seo\src\builders\indexable-link-builder.php(115): apply_filters('the_content', 'text parameter ...')
#15 C:\apache\htdocs\wordpress\wp-content\plugins\wordpress-seo\src\actions\indexing\abstract-link-indexing-action.php(65): Yoast\WP\SEO\Builders\Indexable_Link_Builder->build(Object(Yoast\WP\SEO\Models\Indexable), 'text parameter ...')
#16 C:\apache\htdocs\wordpress\wp-content\plugins\wordpress-seo\src\integrations\admin\background-indexing-integration.php(219): Yoast\WP\SEO\Actions\Indexing\Abstract_Link_Indexing_Action->index()
#17 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(310): Yoast\WP\SEO\Integrations\Admin\Background_Indexing_Integration->index()
#18 C:\apache\htdocs\oikcom\wp-includes\class-wp-hook.php(334): WP_Hook->apply_filters('', Array)
#19 C:\apache\htdocs\oikcom\wp-includes\plugin.php(565): WP_Hook->do_action(Array)
#20 C:\apache\htdocs\oikcom\wp-cron.php(191): do_action_ref_array('wpseo_indexable...', Array)
#21 {main}
  thrown in C:\apache\htdocs\wordpress\wp-content\plugins\oik-sc-help\shortcodes\easy-digital-downloads.php on line 329
```

**Comment by bobbingwide** [comment]
Easy Digital Downloads ( v2.9.26 ) was not activated on `s.b/oikcom` so the function `edd_get_option` didn't exist.
The code should cater for this.
Also EDD needs updating to support PHP 8.1 (v3.2.1) and PHP 8.2 ( future version?)

Note: There were plenty of errors from EDD v3.2.1 when I ran `wp edd v30_migration` with PHP 8.2
eg
```
Deprecated: Creation of dynamic property EDD\Component::$types is deprecated 
in C:\apache\htdocs\wordpress\wp-content\plugins\easy-digital-downloads\includes\orders\functions\types.php on line 62
```
And I keep getting
WordPress database error Table 'wp.wp_edd_ordermeta' doesn't exist for query SELECT COUNT(meta_id) FROM wp_edd_ordermeta WHERE meta_key = '_edd_complete_actions_run' made by shutdown_action_hook, do_action('shutdown'),

**Comment by bobbingwide** [comment]
Delivered in v1.20.7
